import localFont from 'next/font/local'
import "./globals.css";

const openSauce = localFont({ src: './OpenSauceSans-Regular.ttf' })

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={openSauce.className}>{children}</body>
    </html>
  );
}
